<?php
/**
 * @file
 * Code for the uWaterloo Content Type Web Page feature.
 */

include_once('uw_ct_web_page.features.inc');

/**
 * Implements hook_form_FORM_ID_alter().
 * FORM_ID = uw_web_page_node_form (node add/edit form).
 */
function uw_ct_web_page_form_uw_web_page_node_form_alter(&$form, &$form_state, $form_id) {
  global $language;
  $langcode = $language->language;

  $sidebar = $form['#groups']['group_sidebar'];

  // We expand the sidebar field group if any of its fields contain content.
  foreach ($sidebar -> children as $field) {
    if (!empty($form[$field][$langcode][0]['#default_value'])) {
      $sidebar -> format_settings['formatter'] = 'collapsible';
      break;
    }
  }
  // Change file_upload_description.
  // When you are creating a webpage all fields are in the undefined language.
  // #file_upload_description and #file_upload_title do not exist when you creating the webpage.
  if (isset($form['field_image'][$langcode])) {
    $form['field_image'][$langcode]['#file_upload_description'] = str_replace('Files', 'Images', $form['field_image'][$langcode]['#file_upload_description']);
    $form['field_image'][$langcode]['#file_upload_description'] = str_replace('file', 'image', $form['field_image'][$langcode]['#file_upload_description']);
    $form['field_image'][$langcode]['#file_upload_title'] = 'Add a new image';
  }
  // Disable sticky option.
  $form['options']['sticky']['#disabled'] = TRUE;
  $form['options']['sticky']['#value'] = FALSE;
  $form['options']['sticky']['#description'] = t('This content type does not use the sticky option.');

  // Disable front page option.
  $form['options']['promote']['#disabled'] = TRUE;
  $form['options']['promote']['#value'] = FALSE;
  $form['options']['promote']['#description'] = t('This content type does not use the front page option.');

  // Load JavaScript to make wide pages handling cleaner.
  $form['#after_build'][] = 'uw_ct_web_page_wide_handler';

	// Setting the default images for metatag twitter cards and open-graph.
	// The node:field_image is an image within the node body and the
	// node:field_event_image is the social media listing page image.
	if (module_exists('metatag') && $form_id == 'uw_web_page_node_form') {
		$form['metatags'][LANGUAGE_NONE]['open-graph']['og:image']['value']['#default_value'] = '[node:field_event_image],[node:field_image]';
		$form['metatags'][LANGUAGE_NONE]['twitter-cards']['twitter:image:src']['value']['#default_value'] = '[node:field_event_image],[node:field_image]';
	}
}

/**
 * Add Javascript to wide pages.
 * @param $element
 * @return $element
 */
function uw_ct_web_page_wide_handler($element) {
  drupal_add_js(drupal_get_path('module', 'uw_ct_web_page') . '/uw_ct_web_page.js');
  return($element);
}

/**
 * Implements hook_page_build().
 *
 * Add the breadcrumbs for the management view.
 */
function uw_ct_web_page_page_build() {

  $path = current_path();

  if ($path == 'admin/workbench/manage/web-pages') {
    $breadcrumb = drupal_get_breadcrumb();
    $breadcrumb[1] = l('Administration', 'admin');
    $breadcrumb[2] = l('My Workbench', 'admin/workbench');
    $breadcrumb[3] = l('Create/Manage Content', 'admin/workbench/create');
    drupal_set_breadcrumb($breadcrumb);
  }
}

/**
 * Implements hook_block_info().
 */
function uw_ct_web_page_block_info() {
  // These blocks change depending on the page being viewed, so we cache per page (instead of the default per role).
  $blocks['uw_sidebar_block'] = array(
    'info' => t('uWaterloo Sidebar Content'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['uw_sidebar_related_links'] = array(
    'info' => t('uWaterloo Sidebar Related Links'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function uw_ct_web_page_block_view($delta = '') {
  // The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'uw_sidebar_block':
      $block['content'] = uw_ct_web_page_sidebar_content('field_sidebar_content', array('field_sidebar_content_value'));
      break;
    case 'uw_sidebar_related_links':
      $block['subject'] = t('Related links');
      $block['content'] = uw_ct_web_page_sidebar_content('field_related_link', array('field_related_link_url', 'field_related_link_title'));
      break;
  }
  return $block;
}

function uw_ct_web_page_sidebar_content($field, $cols) {
  if (arg(0) === 'node') {
    $params = array('nid' => intval(arg(1)));

    switch (arg(2)) {
      case 'revisions':
        $revision_id = ':revision_id';
        $params['revision_id'] = intval(arg(3));
        break;
      case 'draft':
        $revision_id = "(SELECT MAX(vid) FROM {node_revision} WHERE nid = :nid)";
        break;
      default:
        $revision_id = "(SELECT vid FROM {node} WHERE nid = :nid)";
    }

    $sql = "SELECT " . implode(', ', $cols) . "
      FROM (
        SELECT * FROM {field_data_$field}
      UNION
        SELECT * FROM {field_revision_$field}
      ) AS combined
      WHERE (bundle = 'uw_web_page')
        AND (revision_id = $revision_id)
        AND (entity_id = :nid)";
    foreach ($cols as $col) {
      $sql .= " AND ($col IS NOT NULL)";
    }
    $sql .= " ORDER BY delta";

    $result = db_query($sql, $params);

    $output = '';

    switch ($field) {
      case 'field_sidebar_content':
        foreach ($result as $record) {
          $output .= $record->field_sidebar_content_value;
        }
        break;
      case 'field_related_link':
        $output = array();
        foreach ($result as $record) {
          $output[] = l($record->field_related_link_title, $record->field_related_link_url);
        }
        if ($output) {
          $output = '<ul><li>' . implode('</li><li>', $output) . '</li></ul>';
        }
        break;
    }

    if ($output) {
      return array('#markup' => check_markup($output, 'uw_tf_standard_sidebar'));
    }
  }
}

/**
 * Implements hook_element_info_alter().
 */
function uw_ct_web_page_element_info_alter(&$type) {
  if (isset($type['link_field'])) {
    $type['link_field']['#process'][] = 'uw_ct_web_page_link_field_process';
  }
}

/**
 * Process the link type element before displaying the field.
 *
 * Build the form element. When creating a form using FAPI #process,
 * note that $element['#value'] is already set.
 *
 * The $fields array is in $complete_form['#field_info'][$element['#field_name']].
 */
function uw_ct_web_page_link_field_process($element, $form_state, $complete_form) {
  switch ($element['#field_name']) {
    case 'field_related_link':
      $element['title']['#title'] = t('Link text');
      $element['url']['#title'] = t('URL');
      $element['title']['#description'] = t('The link text is limited to '. $element['title']['#maxlength'].' characters maximum.');
      break;
  }
  return $element;
}

/**
 * Prepare text for teasers, using either the summary or trimmed value.
 *
 * Filter, trim, and convert <h#> to <p>.
 *
 * @param $content array
 *   Views field array or an array with keys summary or value from which to
 *   generate the summary.
 *
 * @return string|null
 *   The summary or NULL when the field is not set.
 */
function uw_ct_web_page_filter_summary(array $content) {
  if (isset($content['summary']) && (string) $content['summary'] !== '') {
    $summary = $content['summary'];
    $needs_trim = FALSE;
  }
  elseif (isset($content['value']) && (string) $content['value'] !== '') {
    $summary = $content['value'];
    $needs_trim = TRUE;
  }
  elseif (isset($content[0]['raw']['summary']) && (string) $content[0]['raw']['summary'] !== '') {
    $summary = $content[0]['raw']['summary'];
    $needs_trim = FALSE;
  }
  elseif (isset($content[0]['raw']['value']) && (string) $content[0]['raw']['value'] !== '') {
    $summary = $content[0]['raw']['value'];
    $needs_trim = TRUE;
  }
  else {
    return NULL;
  }
  $summary = check_markup(preg_replace(',<(/?)h\d,', '<$1p', $summary), 'uw_tf_basic');
  // Trim only if using the value.
  if ($needs_trim) {
    // Because text_summary can cause unclosed tags (https://www.drupal.org/node/221257), run the HTML corrector filter on the summary.
    $summary = _filter_htmlcorrector(text_summary($summary));
  }
  return $summary;
}
